// Copyright (c) 2026 Leonardo Capossio — bard0 design  hello@bard0.com
// SPDX-License-Identifier: MIT
// AxiZeroWrapper.v
//
// Thin Verilog wrapper around AxiZeroCocotbDUT (SpinalHDL-generated).
// Renames SpinalHDL-style ports (io_masters_N_aw_payload_addr, …) to the
// flat AXI names that cocotbext-axi expects (m0_awaddr, …).
//
// Topology: 2 masters (M0, M1) × 2 slaves (S0, S1)
// M0/M1 : masterIdWidth = 4
// S0/S1 : slaveIdWidth  = 5  (4 + 1 master-index bit)
//
// Signal prefixes used by the cocotb test:
//   m0_*, m1_*  →  AXI4 master ports (inputs to DUT)
//   s0_*, s1_*  →  AXI4 slave  ports (outputs from DUT)
// ---------------------------------------------------------------------------

`timescale 1ns/1ps

module AxiZeroWrapper (
  input  wire        clk,
  input  wire        resetn,    // active-low synchronous reset

  // ── Master 0 ─────────────────────────────────────────────────────────────
  // AW
  input  wire        m0_awvalid,
  output wire        m0_awready,
  input  wire [31:0] m0_awaddr,
  input  wire [3:0]  m0_awid,
  input  wire [7:0]  m0_awlen,
  input  wire [2:0]  m0_awsize,
  input  wire [1:0]  m0_awburst,
  input  wire [0:0]  m0_awlock,
  input  wire [3:0]  m0_awcache,
  input  wire [2:0]  m0_awprot,
  input  wire [3:0]  m0_awqos,
  input  wire [3:0]  m0_awregion,
  // W
  input  wire        m0_wvalid,
  output wire        m0_wready,
  input  wire [31:0] m0_wdata,
  input  wire [3:0]  m0_wstrb,
  input  wire        m0_wlast,
  // B
  output wire        m0_bvalid,
  input  wire        m0_bready,
  output wire [3:0]  m0_bid,
  output wire [1:0]  m0_bresp,
  // AR
  input  wire        m0_arvalid,
  output wire        m0_arready,
  input  wire [31:0] m0_araddr,
  input  wire [3:0]  m0_arid,
  input  wire [7:0]  m0_arlen,
  input  wire [2:0]  m0_arsize,
  input  wire [1:0]  m0_arburst,
  input  wire [0:0]  m0_arlock,
  input  wire [3:0]  m0_arcache,
  input  wire [2:0]  m0_arprot,
  input  wire [3:0]  m0_arqos,
  input  wire [3:0]  m0_arregion,
  // R
  output wire        m0_rvalid,
  input  wire        m0_rready,
  output wire [31:0] m0_rdata,
  output wire [3:0]  m0_rid,
  output wire [1:0]  m0_rresp,
  output wire        m0_rlast,

  // ── Master 1 ─────────────────────────────────────────────────────────────
  input  wire        m1_awvalid,
  output wire        m1_awready,
  input  wire [31:0] m1_awaddr,
  input  wire [3:0]  m1_awid,
  input  wire [7:0]  m1_awlen,
  input  wire [2:0]  m1_awsize,
  input  wire [1:0]  m1_awburst,
  input  wire [0:0]  m1_awlock,
  input  wire [3:0]  m1_awcache,
  input  wire [2:0]  m1_awprot,
  input  wire [3:0]  m1_awqos,
  input  wire [3:0]  m1_awregion,
  input  wire        m1_wvalid,
  output wire        m1_wready,
  input  wire [31:0] m1_wdata,
  input  wire [3:0]  m1_wstrb,
  input  wire        m1_wlast,
  output wire        m1_bvalid,
  input  wire        m1_bready,
  output wire [3:0]  m1_bid,
  output wire [1:0]  m1_bresp,
  input  wire        m1_arvalid,
  output wire        m1_arready,
  input  wire [31:0] m1_araddr,
  input  wire [3:0]  m1_arid,
  input  wire [7:0]  m1_arlen,
  input  wire [2:0]  m1_arsize,
  input  wire [1:0]  m1_arburst,
  input  wire [0:0]  m1_arlock,
  input  wire [3:0]  m1_arcache,
  input  wire [2:0]  m1_arprot,
  input  wire [3:0]  m1_arqos,
  input  wire [3:0]  m1_arregion,
  output wire        m1_rvalid,
  input  wire        m1_rready,
  output wire [31:0] m1_rdata,
  output wire [3:0]  m1_rid,
  output wire [1:0]  m1_rresp,
  output wire        m1_rlast,

  // ── Slave 0 (idWidth=5) ──────────────────────────────────────────────────
  output wire        s0_awvalid,
  input  wire        s0_awready,
  output wire [31:0] s0_awaddr,
  output wire [4:0]  s0_awid,
  output wire [7:0]  s0_awlen,
  output wire [2:0]  s0_awsize,
  output wire [1:0]  s0_awburst,
  output wire [0:0]  s0_awlock,
  output wire [3:0]  s0_awcache,
  output wire [2:0]  s0_awprot,
  output wire [3:0]  s0_awqos,
  output wire        s0_wvalid,
  input  wire        s0_wready,
  output wire [31:0] s0_wdata,
  output wire [3:0]  s0_wstrb,
  output wire        s0_wlast,
  input  wire        s0_bvalid,
  output wire        s0_bready,
  input  wire [4:0]  s0_bid,
  input  wire [1:0]  s0_bresp,
  output wire        s0_arvalid,
  input  wire        s0_arready,
  output wire [31:0] s0_araddr,
  output wire [4:0]  s0_arid,
  output wire [7:0]  s0_arlen,
  output wire [2:0]  s0_arsize,
  output wire [1:0]  s0_arburst,
  output wire [0:0]  s0_arlock,
  output wire [3:0]  s0_arcache,
  output wire [2:0]  s0_arprot,
  output wire [3:0]  s0_arqos,
  input  wire        s0_rvalid,
  output wire        s0_rready,
  input  wire [31:0] s0_rdata,
  input  wire [4:0]  s0_rid,
  input  wire [1:0]  s0_rresp,
  input  wire        s0_rlast,

  // ── Slave 1 (idWidth=5) ──────────────────────────────────────────────────
  output wire        s1_awvalid,
  input  wire        s1_awready,
  output wire [31:0] s1_awaddr,
  output wire [4:0]  s1_awid,
  output wire [7:0]  s1_awlen,
  output wire [2:0]  s1_awsize,
  output wire [1:0]  s1_awburst,
  output wire [0:0]  s1_awlock,
  output wire [3:0]  s1_awcache,
  output wire [2:0]  s1_awprot,
  output wire [3:0]  s1_awqos,
  output wire        s1_wvalid,
  input  wire        s1_wready,
  output wire [31:0] s1_wdata,
  output wire [3:0]  s1_wstrb,
  output wire        s1_wlast,
  input  wire        s1_bvalid,
  output wire        s1_bready,
  input  wire [4:0]  s1_bid,
  input  wire [1:0]  s1_bresp,
  output wire        s1_arvalid,
  input  wire        s1_arready,
  output wire [31:0] s1_araddr,
  output wire [4:0]  s1_arid,
  output wire [7:0]  s1_arlen,
  output wire [2:0]  s1_arsize,
  output wire [1:0]  s1_arburst,
  output wire [0:0]  s1_arlock,
  output wire [3:0]  s1_arcache,
  output wire [2:0]  s1_arprot,
  output wire [3:0]  s1_arqos,
  input  wire        s1_rvalid,
  output wire        s1_rready,
  input  wire [31:0] s1_rdata,
  input  wire [4:0]  s1_rid,
  input  wire [1:0]  s1_rresp,
  input  wire        s1_rlast
);

  AxiZeroMixedTop dut (
    .clk    (clk),
    .resetn (resetn),

    // Master 0
    .io_masters_0_aw_valid              (m0_awvalid),
    .io_masters_0_aw_ready              (m0_awready),
    .io_masters_0_aw_payload_addr       (m0_awaddr),
    .io_masters_0_aw_payload_id         (m0_awid),
    .io_masters_0_aw_payload_len        (m0_awlen),
    .io_masters_0_aw_payload_size       (m0_awsize),
    .io_masters_0_aw_payload_burst      (m0_awburst),
    .io_masters_0_aw_payload_lock       (m0_awlock),
    .io_masters_0_aw_payload_cache      (m0_awcache),
    .io_masters_0_aw_payload_prot       (m0_awprot),
    .io_masters_0_aw_payload_qos        (m0_awqos),
    .io_masters_0_aw_payload_region     (m0_awregion),
    .io_masters_0_w_valid               (m0_wvalid),
    .io_masters_0_w_ready               (m0_wready),
    .io_masters_0_w_payload_data        (m0_wdata),
    .io_masters_0_w_payload_strb        (m0_wstrb),
    .io_masters_0_w_payload_last        (m0_wlast),
    .io_masters_0_b_valid               (m0_bvalid),
    .io_masters_0_b_ready               (m0_bready),
    .io_masters_0_b_payload_id          (m0_bid),
    .io_masters_0_b_payload_resp        (m0_bresp),
    .io_masters_0_ar_valid              (m0_arvalid),
    .io_masters_0_ar_ready              (m0_arready),
    .io_masters_0_ar_payload_addr       (m0_araddr),
    .io_masters_0_ar_payload_id         (m0_arid),
    .io_masters_0_ar_payload_len        (m0_arlen),
    .io_masters_0_ar_payload_size       (m0_arsize),
    .io_masters_0_ar_payload_burst      (m0_arburst),
    .io_masters_0_ar_payload_lock       (m0_arlock),
    .io_masters_0_ar_payload_cache      (m0_arcache),
    .io_masters_0_ar_payload_prot       (m0_arprot),
    .io_masters_0_ar_payload_qos        (m0_arqos),
    .io_masters_0_ar_payload_region     (m0_arregion),
    .io_masters_0_r_valid               (m0_rvalid),
    .io_masters_0_r_ready               (m0_rready),
    .io_masters_0_r_payload_data        (m0_rdata),
    .io_masters_0_r_payload_id          (m0_rid),
    .io_masters_0_r_payload_resp        (m0_rresp),
    .io_masters_0_r_payload_last        (m0_rlast),

    // Master 1
    .io_masters_1_aw_valid              (m1_awvalid),
    .io_masters_1_aw_ready              (m1_awready),
    .io_masters_1_aw_payload_addr       (m1_awaddr),
    .io_masters_1_aw_payload_id         (m1_awid),
    .io_masters_1_aw_payload_len        (m1_awlen),
    .io_masters_1_aw_payload_size       (m1_awsize),
    .io_masters_1_aw_payload_burst      (m1_awburst),
    .io_masters_1_aw_payload_lock       (m1_awlock),
    .io_masters_1_aw_payload_cache      (m1_awcache),
    .io_masters_1_aw_payload_prot       (m1_awprot),
    .io_masters_1_aw_payload_qos        (m1_awqos),
    .io_masters_1_aw_payload_region     (m1_awregion),
    .io_masters_1_w_valid               (m1_wvalid),
    .io_masters_1_w_ready               (m1_wready),
    .io_masters_1_w_payload_data        (m1_wdata),
    .io_masters_1_w_payload_strb        (m1_wstrb),
    .io_masters_1_w_payload_last        (m1_wlast),
    .io_masters_1_b_valid               (m1_bvalid),
    .io_masters_1_b_ready               (m1_bready),
    .io_masters_1_b_payload_id          (m1_bid),
    .io_masters_1_b_payload_resp        (m1_bresp),
    .io_masters_1_ar_valid              (m1_arvalid),
    .io_masters_1_ar_ready              (m1_arready),
    .io_masters_1_ar_payload_addr       (m1_araddr),
    .io_masters_1_ar_payload_id         (m1_arid),
    .io_masters_1_ar_payload_len        (m1_arlen),
    .io_masters_1_ar_payload_size       (m1_arsize),
    .io_masters_1_ar_payload_burst      (m1_arburst),
    .io_masters_1_ar_payload_lock       (m1_arlock),
    .io_masters_1_ar_payload_cache      (m1_arcache),
    .io_masters_1_ar_payload_prot       (m1_arprot),
    .io_masters_1_ar_payload_qos        (m1_arqos),
    .io_masters_1_ar_payload_region     (m1_arregion),
    .io_masters_1_r_valid               (m1_rvalid),
    .io_masters_1_r_ready               (m1_rready),
    .io_masters_1_r_payload_data        (m1_rdata),
    .io_masters_1_r_payload_id          (m1_rid),
    .io_masters_1_r_payload_resp        (m1_rresp),
    .io_masters_1_r_payload_last        (m1_rlast),

    // Slave 0
    .io_slaves_0_aw_valid               (s0_awvalid),
    .io_slaves_0_aw_ready               (s0_awready),
    .io_slaves_0_aw_payload_addr        (s0_awaddr),
    .io_slaves_0_aw_payload_id          (s0_awid),
    .io_slaves_0_aw_payload_len         (s0_awlen),
    .io_slaves_0_aw_payload_size        (s0_awsize),
    .io_slaves_0_aw_payload_burst       (s0_awburst),
    .io_slaves_0_aw_payload_lock        (s0_awlock),
    .io_slaves_0_aw_payload_cache       (s0_awcache),
    .io_slaves_0_aw_payload_prot        (s0_awprot),
    .io_slaves_0_aw_payload_qos         (s0_awqos),
    .io_slaves_0_w_valid                (s0_wvalid),
    .io_slaves_0_w_ready                (s0_wready),
    .io_slaves_0_w_payload_data         (s0_wdata),
    .io_slaves_0_w_payload_strb         (s0_wstrb),
    .io_slaves_0_w_payload_last         (s0_wlast),
    .io_slaves_0_b_valid                (s0_bvalid),
    .io_slaves_0_b_ready                (s0_bready),
    .io_slaves_0_b_payload_id           (s0_bid),
    .io_slaves_0_b_payload_resp         (s0_bresp),
    .io_slaves_0_ar_valid               (s0_arvalid),
    .io_slaves_0_ar_ready               (s0_arready),
    .io_slaves_0_ar_payload_addr        (s0_araddr),
    .io_slaves_0_ar_payload_id          (s0_arid),
    .io_slaves_0_ar_payload_len         (s0_arlen),
    .io_slaves_0_ar_payload_size        (s0_arsize),
    .io_slaves_0_ar_payload_burst       (s0_arburst),
    .io_slaves_0_ar_payload_lock        (s0_arlock),
    .io_slaves_0_ar_payload_cache       (s0_arcache),
    .io_slaves_0_ar_payload_prot        (s0_arprot),
    .io_slaves_0_ar_payload_qos         (s0_arqos),
    .io_slaves_0_r_valid                (s0_rvalid),
    .io_slaves_0_r_ready                (s0_rready),
    .io_slaves_0_r_payload_data         (s0_rdata),
    .io_slaves_0_r_payload_id           (s0_rid),
    .io_slaves_0_r_payload_resp         (s0_rresp),
    .io_slaves_0_r_payload_last         (s0_rlast),

    // Slave 1
    .io_slaves_1_aw_valid               (s1_awvalid),
    .io_slaves_1_aw_ready               (s1_awready),
    .io_slaves_1_aw_payload_addr        (s1_awaddr),
    .io_slaves_1_aw_payload_id          (s1_awid),
    .io_slaves_1_aw_payload_len         (s1_awlen),
    .io_slaves_1_aw_payload_size        (s1_awsize),
    .io_slaves_1_aw_payload_burst       (s1_awburst),
    .io_slaves_1_aw_payload_lock        (s1_awlock),
    .io_slaves_1_aw_payload_cache       (s1_awcache),
    .io_slaves_1_aw_payload_prot        (s1_awprot),
    .io_slaves_1_aw_payload_qos         (s1_awqos),
    .io_slaves_1_w_valid                (s1_wvalid),
    .io_slaves_1_w_ready                (s1_wready),
    .io_slaves_1_w_payload_data         (s1_wdata),
    .io_slaves_1_w_payload_strb         (s1_wstrb),
    .io_slaves_1_w_payload_last         (s1_wlast),
    .io_slaves_1_b_valid                (s1_bvalid),
    .io_slaves_1_b_ready                (s1_bready),
    .io_slaves_1_b_payload_id           (s1_bid),
    .io_slaves_1_b_payload_resp         (s1_bresp),
    .io_slaves_1_ar_valid               (s1_arvalid),
    .io_slaves_1_ar_ready               (s1_arready),
    .io_slaves_1_ar_payload_addr        (s1_araddr),
    .io_slaves_1_ar_payload_id          (s1_arid),
    .io_slaves_1_ar_payload_len         (s1_arlen),
    .io_slaves_1_ar_payload_size        (s1_arsize),
    .io_slaves_1_ar_payload_burst       (s1_arburst),
    .io_slaves_1_ar_payload_lock        (s1_arlock),
    .io_slaves_1_ar_payload_cache       (s1_arcache),
    .io_slaves_1_ar_payload_prot        (s1_arprot),
    .io_slaves_1_ar_payload_qos         (s1_arqos),
    .io_slaves_1_r_valid                (s1_rvalid),
    .io_slaves_1_r_ready                (s1_rready),
    .io_slaves_1_r_payload_data         (s1_rdata),
    .io_slaves_1_r_payload_id           (s1_rid),
    .io_slaves_1_r_payload_resp         (s1_rresp),
    .io_slaves_1_r_payload_last         (s1_rlast)
  );

endmodule
