#!/usr/bin/env python3
# Copyright (c) 2026 Leonardo Capossio - bard0 design  hello@bard0.com
# SPDX-License-Identifier: MIT
"""
run_axi3_test.py -- Build, program, and run the AXI3 adapter HW test on Arty A7-100T.

Steps:
  1. Vivado: create project + synth + impl + bitstream  (create_project_axi3.tcl)
  2. mb-gcc: compile main_axi3.c -> main_axi3_le.elf
  3. xsdb:   program bitstream + ELF, wait, read g_fail / g_pass
"""

import os
import pathlib
import subprocess
import sys
import time

from find_xilinx_tools import require_tools

# -- Paths --
SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR / ".." / ".." / ".."
SW_DIR     = REPO_ROOT / "sw" / "arty_a7"
SRC_DIR    = SW_DIR / "src"

VIVADO_BIN, XSDB_BIN, MBGCC_BIN = require_tools()

PROJ_DIR = SCRIPT_DIR / "axizero_arty_axi3"
BIT_FILE = PROJ_DIR / "axizero_arty_axi3.runs" / "impl_1" / "system_wrapper.bit"
ELF_FILE = SW_DIR / "build" / "main_axi3_le.elf"

CREATE_TCL = SCRIPT_DIR / "create_project_axi3.tcl"


def run(cmd, cwd=None, timeout=None, desc="", env=None):
    print(f"\n{'='*60}")
    print(f"  {desc}")
    print(f"  cmd: {' '.join(str(c) for c in cmd)}")
    print(f"{'='*60}\n")
    result = subprocess.run(
        [str(c) for c in cmd],
        cwd=str(cwd) if cwd else None,
        timeout=timeout,
        env=env,
    )
    if result.returncode != 0:
        print(f"\n*** FAILED (rc={result.returncode}): {desc}")
        sys.exit(result.returncode)
    return result


def step_vivado():
    if BIT_FILE.exists():
        print(f"[skip] Bitstream already exists: {BIT_FILE}")
        return
    # Fix HOME for Vivado child processes: Unix-style /c/Users/... breaks tclapp::load_apps
    env = dict(os.environ)
    if "HOME" in env and env["HOME"].startswith("/"):
        env["HOME"] = str(pathlib.Path.home())
    run(
        [VIVADO_BIN, "-mode", "batch", "-source", str(CREATE_TCL)],
        cwd=REPO_ROOT,
        timeout=3600,
        desc="Vivado: create project + synth + impl + bitstream",
        env=env,
    )
    if not BIT_FILE.exists():
        print(f"*** ERROR: bitstream not found at {BIT_FILE}")
        sys.exit(1)
    print(f"[ok] Bitstream: {BIT_FILE}")


def step_compile():
    ELF_FILE.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            MBGCC_BIN,
            "-O2", "-mlittle-endian", "-mxl-soft-mul",
            "-nostdlib",
            "-I", str(SRC_DIR),
            str(SRC_DIR / "crt0.S"),
            str(SRC_DIR / "main_axi3.c"),
            "-T", str(SRC_DIR / "arty.ld"),
            "-lgcc",
            "-o", str(ELF_FILE),
        ],
        cwd=SW_DIR,
        timeout=60,
        desc="mb-gcc: compile main_axi3_le.elf",
    )
    print(f"[ok] ELF: {ELF_FILE}  ({ELF_FILE.stat().st_size} bytes)")


def find_symbols():
    nm_bin = MBGCC_BIN.parent / ("mb-nm.exe" if sys.platform == "win32" else "mb-nm")
    result = subprocess.run(
        [str(nm_bin), str(ELF_FILE)],
        capture_output=True, text=True, timeout=10,
    )
    addrs = {}
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3:
            name = parts[2]
            if name in ("g_fail", "g_pass"):
                addrs[name] = int(parts[0], 16)
    if "g_fail" not in addrs or "g_pass" not in addrs:
        print(f"*** Could not find g_fail/g_pass in ELF symbols")
        for line in result.stdout.splitlines()[-20:]:
            print(f"    {line}")
        sys.exit(1)
    print(f"[ok] g_fail @ 0x{addrs['g_fail']:08X},  g_pass @ 0x{addrs['g_pass']:08X}")
    return addrs


def step_run(addrs):
    g_fail_addr = addrs["g_fail"]
    g_pass_addr = addrs["g_pass"]

    xsdb_tcl = SCRIPT_DIR / "_axi3_xsdb_temp.tcl"
    xsdb_tcl.write_text(f"""\
# Auto-generated by run_axi3_test.py
connect
after 500
# Select the Arty A7-100T (xc7a100t) when multiple FPGA devices are on the
# JTAG chain.
targets -set -filter {{name =~ "xc7a100t*"}}
after 200
fpga {str(BIT_FILE).replace(chr(92), '/')}
after 1000

targets -set -filter {{name =~ "MicroBlaze #0"}}
after 200

rst -processor
after 200
dow {str(ELF_FILE).replace(chr(92), '/')}
after 200
con

# Wait for tests: MB boots with 3s delay + test execution (~10s)
puts "\\nWaiting 25s for test completion..."
after 25000

rst -processor
after 500

set fail_val [mrd -value 0x{g_fail_addr:08X}]
set pass_val [mrd -value 0x{g_pass_addr:08X}]

puts "\\n=========================================="
puts "  AXI3 Adapter HW Test Results"
puts "=========================================="
puts "  g_fail = $fail_val   (@ 0x{g_fail_addr:08X})"
puts "  g_pass = $pass_val   (@ 0x{g_pass_addr:08X})"
puts "=========================================="

if {{$fail_val == 0}} {{
    puts "  *** ALL AXI3 TESTS PASSED ***"
}} else {{
    puts "  *** AXI3 FAILURES DETECTED ***"
}}
puts ""

disconnect
exit
""", encoding="utf-8")

    run(
        [XSDB_BIN, str(xsdb_tcl)],
        cwd=SCRIPT_DIR,
        timeout=180,
        desc="xsdb: program + run + read results",
    )

    xsdb_tcl.unlink(missing_ok=True)


def main():
    print("axiZero AXI3 adapter hardware test -- Arty A7-100T")
    print(f"  Vivado:  {VIVADO_BIN}")
    print(f"  mb-gcc:  {MBGCC_BIN}")
    print(f"  xsdb:    {XSDB_BIN}")
    print()

    step_vivado()
    step_compile()
    addrs = find_symbols()
    step_run(addrs)


if __name__ == "__main__":
    main()
