#!/usr/bin/env python3
# Copyright (c) 2026 Leonardo Capossio - bard0 design  hello@bard0.com
# SPDX-License-Identifier: MIT
"""
run_base_test.py -- Build, program, and run the base hardware test on Arty A7-100T.

Steps:
  1. Vivado: create project + synth + impl + bitstream  (create_project.tcl)
  2. mb-gcc: compile main.c -> main_le.elf
  3. xsdb:   program bitstream + ELF, wait, read g_fail / g_pass
"""

import os
import pathlib
import subprocess
import sys
import time

from find_xilinx_tools import require_tools

# -- Paths --
SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR / ".." / ".." / ".."
SW_DIR     = REPO_ROOT / "sw" / "arty_a7"
SRC_DIR    = SW_DIR / "src"

VIVADO_BIN, XSDB_BIN, MBGCC_BIN = require_tools()

PROJ_DIR = SCRIPT_DIR / "axizero_arty"
BIT_FILE = PROJ_DIR / "axizero_arty.runs" / "impl_1" / "system_wrapper.bit"
ELF_FILE = SW_DIR / "build" / "main_le.elf"

CREATE_TCL = SCRIPT_DIR / "create_project.tcl"


def run(cmd, cwd=None, timeout=None, desc="", env=None):
    print(f"\n{'='*60}")
    print(f"  {desc}")
    print(f"  cmd: {' '.join(str(c) for c in cmd)}")
    print(f"{'='*60}\n")
    result = subprocess.run(
        [str(c) for c in cmd],
        cwd=str(cwd) if cwd else None,
        timeout=timeout,
        env=env,
    )
    if result.returncode != 0:
        print(f"\n*** FAILED (rc={result.returncode}): {desc}")
        sys.exit(result.returncode)
    return result


def step_vivado():
    if BIT_FILE.exists():
        print(f"[skip] Bitstream already exists: {BIT_FILE}")
        return
    env = dict(os.environ)
    if "HOME" in env and env["HOME"].startswith("/"):
        env["HOME"] = str(pathlib.Path.home())
    run(
        [VIVADO_BIN, "-mode", "batch", "-source", str(CREATE_TCL)],
        cwd=REPO_ROOT,
        timeout=3600,
        desc="Vivado: create project + synth + impl + bitstream",
        env=env,
    )
    if not BIT_FILE.exists():
        print(f"*** ERROR: bitstream not found at {BIT_FILE}")
        sys.exit(1)
    print(f"[ok] Bitstream: {BIT_FILE}")


def step_compile():
    ELF_FILE.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            MBGCC_BIN,
            "-O2", "-mlittle-endian", "-mxl-soft-mul",
            "-nostdlib",
            "-I", str(SRC_DIR),
            str(SRC_DIR / "crt0.S"),
            str(SRC_DIR / "main.c"),
            "-T", str(SRC_DIR / "arty.ld"),
            "-lgcc",
            "-o", str(ELF_FILE),
        ],
        cwd=SW_DIR,
        timeout=60,
        desc="mb-gcc: compile main_le.elf",
    )
    print(f"[ok] ELF: {ELF_FILE}  ({ELF_FILE.stat().st_size} bytes)")


def find_symbols():
    nm_bin = MBGCC_BIN.parent / ("mb-nm.exe" if sys.platform == "win32" else "mb-nm")
    result = subprocess.run(
        [str(nm_bin), str(ELF_FILE)],
        capture_output=True, text=True, timeout=10,
    )
    addrs = {}
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3:
            name = parts[2]
            if name in ("g_fail", "g_pass"):
                addrs[name] = int(parts[0], 16)
    if "g_fail" not in addrs or "g_pass" not in addrs:
        print(f"*** Could not find g_fail/g_pass in ELF symbols")
        for line in result.stdout.splitlines()[-20:]:
            print(f"    {line}")
        sys.exit(1)
    print(f"[ok] g_fail @ 0x{addrs['g_fail']:08X},  g_pass @ 0x{addrs['g_pass']:08X}")
    return addrs


def step_run(addrs):
    g_fail_addr = addrs["g_fail"]
    g_pass_addr = addrs["g_pass"]

    xsdb_tcl = SCRIPT_DIR / "_base_xsdb_temp.tcl"
    xsdb_tcl.write_text(f"""\
# Auto-generated by run_base_test.py
connect
after 500
# Select the Arty A7-100T (xc7a100t) when multiple FPGA devices are on the
# JTAG chain (e.g. another Zynq board also plugged in).
targets -set -filter {{name =~ "xc7a100t*"}}
after 200
fpga {str(BIT_FILE).replace(chr(92), '/')}
after 1000

targets -set -filter {{name =~ "MicroBlaze #0"}}
after 200

rst -processor
after 200
dow {str(ELF_FILE).replace(chr(92), '/')}
after 200
con

# Wait for tests: MB boots with 3s delay + test execution (~30s)
puts "\\nWaiting 42s for test completion..."
after 42000

# Halt MicroBlaze without resetting the AXI fabric so the AXI Protocol
# Checker sticky bits (axi_gpio_0 ch2) survive long enough to read.
stop
after 200

# Read AXI GPIO ch2 = pc_status sticky [31:0] (only meaningful when the
# bitstream was built with enable_axi_pc=1; reads as 0 otherwise).
set pc_sticky [mrd -value 0xC0020008]

rst -processor
after 500

set fail_val [mrd -value 0x{g_fail_addr:08X}]
set pass_val [mrd -value 0x{g_pass_addr:08X}]

puts "\\n=========================================="
puts "  Base HW Test Results"
puts "=========================================="
puts "  g_fail = $fail_val   (@ 0x{g_fail_addr:08X})"
puts "  g_pass = $pass_val   (@ 0x{g_pass_addr:08X})"
puts "  axi_pc view = 0x$pc_sticky   (@ 0xC0020008)"
puts "=========================================="

if {{$fail_val == 0}} {{
    puts "  *** ALL BASE TESTS PASSED ***"
}} else {{
    puts "  *** BASE FAILURES DETECTED ***"
}}

# Decode axi_pc_sticky detail view (current build):
#   bit 31      = any_violation across all 160 rules
#   bits 29:0   = sticky_full[59:30]  (rule i visible at view[i-30])
set pc_int [expr {{$pc_sticky & 0xFFFFFFFF}}]

# PG101 rule names for the SYNTHESIZABLE axi_protocol_checker_v2_0 IP.
# Source of truth: ASSIGN_MARKED_DEBUG macros in
#   <Vivado>/data/ip/xilinx/axi_protocol_checker_v2_0/hdl/
#       axi_protocol_checker_v2_0_vl_rfs.sv
# (Note: indices DIFFER from the simulation AXI VIP at axi_vip_v1_0_1_axi4pc.sv.)
array set pc_rule {{
    30 PC_30_AXI_ERRS_BRESP_EXOKAY
    31 PC_31_AXI_ERRS_BVALID_RESET
    32 PC_32_AXI_ERRS_BRESP_AW
    33 PC_33_AXI_ERRS_BID_STABLE
    34 PC_34_AXI_ERRS_BRESP_STABLE
    35 PC_35_AXI_ERRS_BVALID_STABLE
    36 PC_36_AXI_RECM_BREADY_MAX_WAIT
    37 PC_37_AXI_ERRM_ARADDR_BOUNDARY
    38 PC_38_AXI_ERRM_ARADDR_WRAP_ALIGN
    39 PC_39_AXI_ERRM_ARBURST
    40 PC_40_AXI_ERRM_ARLEN_LOCK
    41 PC_41_AXI_ERRM_ARCACHE
    42 PC_42_AXI_ERRM_ARLEN_FIXED
    43 PC_43_AXI_ERRM_ARLEN_WRAP
    44 PC_44_AXI_ERRM_ARSIZE
    45 PC_45_AXI_ERRM_ARVALID_RESET
    46 PC_46_AXI_ERRM_ARADDR_STABLE
    47 PC_47_AXI_ERRM_ARBURST_STABLE
    48 PC_48_AXI_ERRM_ARCACHE_STABLE
    49 PC_49_AXI_ERRM_ARID_STABLE
    50 PC_50_AXI_ERRM_ARLEN_STABLE
    51 PC_51_AXI_ERRM_ARLOCK_STABLE
    52 PC_52_AXI_ERRM_ARPROT_STABLE
    53 PC_53_AXI_ERRM_ARSIZE_STABLE
    54 PC_54_AXI_ERRM_ARQOS_STABLE
    55 PC_55_AXI_ERRM_ARREGION_STABLE
    56 PC_56_AXI_ERRM_ARVALID_STABLE
    57 PC_57_AXI_RECS_ARREADY_MAX_WAIT
    58 PC_58_AXI_ERRS_RDATA_NUM
    59 PC_59_AXI_ERRS_RID
}}

if {{($pc_int >> 31) & 1}} {{
    puts "  *** AXI PROTOCOL VIOLATION(S) DETECTED ***"
    puts "      Detail view = pc_status\[59:30\] in view\[29:0\]:"
    for {{set bi 0}} {{$bi < 30}} {{incr bi}} {{
        if {{($pc_int >> $bi) & 1}} {{
            set rule_idx [expr {{$bi + 30}}]
            set rule_name $pc_rule($rule_idx)
            puts "        pc_status\[$rule_idx\] = $rule_name"
        }}
    }}
}}
puts ""

disconnect
exit
""", encoding="utf-8")

    run(
        [XSDB_BIN, str(xsdb_tcl)],
        cwd=SCRIPT_DIR,
        timeout=120,
        desc="xsdb: program + run + read results",
    )

    xsdb_tcl.unlink(missing_ok=True)


def main():
    print("axiZero base hardware test -- Arty A7-100T")
    print(f"  Vivado:  {VIVADO_BIN}")
    print(f"  mb-gcc:  {MBGCC_BIN}")
    print(f"  xsdb:    {XSDB_BIN}")
    print()

    step_vivado()
    step_compile()
    addrs = find_symbols()
    step_run(addrs)


if __name__ == "__main__":
    main()
