#!/usr/bin/env python3
# Copyright (c) 2026 Leonardo Capossio — bard0 design  hello@bard0.com
# SPDX-License-Identifier: MIT
"""
run_wrr_test.py -- Build, program, and run the WRR hardware test on Arty A7-100T.

Steps:
  1. Vivado: create project + synth + impl + bitstream  (create_project_wrr.tcl)
  2. mb-gcc: compile main_wrr.c -> main_wrr_le.elf
  3. xsdb:   program bitstream + ELF, wait, read g_fail / g_pass
"""

import pathlib
import subprocess
import sys

from find_xilinx_tools import require_tools, vivado_env

# -- Paths --
SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR / ".." / ".." / ".."
SW_DIR     = REPO_ROOT / "sw" / "arty_a7"
SRC_DIR    = SW_DIR / "src"

VIVADO_BIN, XSDB_BIN, MBGCC_BIN = require_tools()

PROJ_DIR = SCRIPT_DIR / "axizero_arty_wrr"
BIT_FILE = PROJ_DIR / "axizero_arty_wrr.runs" / "impl_1" / "system_wrapper.bit"
ELF_FILE = SW_DIR / "build" / "main_wrr_le.elf"

CREATE_TCL = SCRIPT_DIR / "create_project_wrr.tcl"

# -- Helpers --

def run(cmd, cwd=None, timeout=None, desc="", env=None):
    print(f"\n{'='*60}")
    print(f"  {desc}")
    print(f"  cmd: {' '.join(str(c) for c in cmd)}")
    print(f"{'='*60}\n")
    result = subprocess.run(
        [str(c) for c in cmd],
        cwd=str(cwd) if cwd else None,
        timeout=timeout,
        env=env,
    )
    if result.returncode != 0:
        print(f"\n*** FAILED (rc={result.returncode}): {desc}")
        sys.exit(result.returncode)
    return result


def run_capture(cmd, cwd=None, timeout=None, desc="", env=None):
    """Like run(), but returns the output as well as echoing it.

    The verdict lives in xsdb's stdout, not in its exit status: xsdb exits 0
    whether the test passed, failed or never ran, so the caller has to read
    what it printed.
    """
    bar = "=" * 60
    print("")
    print(bar)
    print(f"  {desc}")
    print(f"  cmd: {' '.join(str(c) for c in cmd)}")
    print(bar)
    print("")
    result = subprocess.run(
        [str(c) for c in cmd],
        cwd=str(cwd) if cwd else None,
        timeout=timeout,
        env=env,
        capture_output=True,
        text=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"*** FAILED (rc={result.returncode}): {desc}")
        sys.exit(result.returncode)
    return result.stdout


# -- Step 1: Vivado build --

def step_vivado():
    if BIT_FILE.exists():
        print(f"[skip] Bitstream already exists: {BIT_FILE}")
        return
    env = vivado_env()
    run(
        [VIVADO_BIN, "-mode", "batch", "-source", str(CREATE_TCL)],
        cwd=REPO_ROOT,
        timeout=3600,
        desc="Vivado: create project + synth + impl + bitstream",
        env=env,
    )
    if not BIT_FILE.exists():
        print(f"*** ERROR: bitstream not found at {BIT_FILE}")
        sys.exit(1)
    print(f"[ok] Bitstream: {BIT_FILE}")


# -- Step 2: Compile firmware --

def step_compile():
    ELF_FILE.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            MBGCC_BIN,
            "-O2", "-mlittle-endian", "-mxl-soft-mul",
            "-nostdlib",
            "-I", str(SRC_DIR),
            str(SRC_DIR / "crt0.S"),
            str(SRC_DIR / "main_wrr.c"),
            "-T", str(SRC_DIR / "arty.ld"),
            "-lgcc",
            "-o", str(ELF_FILE),
        ],
        cwd=SW_DIR,
        timeout=60,
        desc="mb-gcc: compile main_wrr_le.elf",
    )
    print(f"[ok] ELF: {ELF_FILE}  ({ELF_FILE.stat().st_size} bytes)")


# -- Step 3: Find g_fail / g_pass symbol addresses --

def find_symbols():
    nm_bin = MBGCC_BIN.parent / ("mb-nm.exe" if sys.platform == "win32" else "mb-nm")
    result = subprocess.run(
        [str(nm_bin), str(ELF_FILE)],
        capture_output=True, text=True, timeout=10,
    )
    addrs = {}
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3:
            name = parts[2]
            if name in ("g_fail", "g_pass"):
                addrs[name] = int(parts[0], 16)
    if "g_fail" not in addrs or "g_pass" not in addrs:
        print("*** Could not find g_fail/g_pass in ELF symbols")
        for line in result.stdout.splitlines()[-20:]:
            print(f"    {line}")
        sys.exit(1)
    print(f"[ok] g_fail @ 0x{addrs['g_fail']:08X},  g_pass @ 0x{addrs['g_pass']:08X}")
    return addrs


# -- Step 4: Program + run + read results via xsdb --

def step_run(addrs):
    g_fail_addr = addrs["g_fail"]
    g_pass_addr = addrs["g_pass"]

    xsdb_tcl = SCRIPT_DIR / "_wrr_xsdb_temp.tcl"
    xsdb_tcl.write_text(f"""\
# Auto-generated by run_wrr_test.py
connect
after 500
# Select the Arty A7-100T (xc7a100t) when multiple FPGA devices are on the
# JTAG chain.
targets -set -filter {{name =~ "xc7a100t*"}}
after 200
fpga {str(BIT_FILE).replace(chr(92), '/')}
after 1000

targets -set -filter {{name =~ "MicroBlaze #0"}}
after 200

rst -processor
after 200
dow {str(ELF_FILE).replace(chr(92), '/')}
after 200
con

# Wait for tests: MB boots with 3s delay + test execution
puts "\\nWaiting 42s for test completion..."
after 42000

rst -processor
after 500

set fail_val [mrd -value 0x{g_fail_addr:08X}]
set pass_val [mrd -value 0x{g_pass_addr:08X}]

puts "\\n=========================================="
puts "  WRR HW Test Results"
puts "=========================================="
puts "  g_fail = $fail_val   (@ 0x{g_fail_addr:08X})"
puts "  g_pass = $pass_val   (@ 0x{g_pass_addr:08X})"
puts "=========================================="

puts "  expected    = g_fail 0, g_pass 3"

if {{$fail_val == 0 && $pass_val == 3}} {{
    puts "  *** ALL WRR TESTS PASSED ***"
}} else {{
    puts "  *** WRR FAILURES DETECTED ***"
}}
puts ""

disconnect
exit
""", encoding="utf-8")

    output = run_capture(
        [XSDB_BIN, str(xsdb_tcl)],
        cwd=SCRIPT_DIR,
        timeout=120,
        desc="xsdb: program + run + read results",
    )

    xsdb_tcl.unlink(missing_ok=True)

    # xsdb exits 0 whether the test passed, failed or never ran, so the
    # verdict has to be read out of what it printed. A wedged bus leaves
    # g_fail = 0 and g_pass = 0, which the banner used to report as success.
    if "no targets found" in output or "*** WRR FAILURES DETECTED ***" in output:
        print("")
        print("*** FAILED: WRR hardware test did not pass")
        sys.exit(1)
    if "*** ALL WRR TESTS PASSED ***" not in output:
        print("")
        print("*** FAILED: WRR pass banner was not observed "
              "(expected g_fail=0 and g_pass=3)")
        sys.exit(1)


# -- Main --

def main():
    print("axiZero WRR hardware test -- Arty A7-100T")
    print(f"  Vivado:  {VIVADO_BIN}")
    print(f"  mb-gcc:  {MBGCC_BIN}")
    print(f"  xsdb:    {XSDB_BIN}")
    print()

    step_vivado()
    step_compile()
    addrs = find_symbols()
    step_run(addrs)


if __name__ == "__main__":
    main()
